title: <p align="center"> Tiffany Chen </p> # your name (or website title) here

logo: "images/wellesley_linkedin photo.jpg" # your photo (or logo) here

description: > # your text below (remove <br> elements if you don't need line breaks)
  <p align="center">
  <a href="https://github.com/tchen3142/tchen3142.github.io/blob/master/pdf/Tiffany-Chen-2023-Resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/tiffanychen8/">LinkedIn</a> |
  <a href="https://github.com/tchen3142">GitHub</a>
  </p>
  
  Recent Master of Science graduate from Columbia University's Operations Research program. I am passionate about product, specifically about consumer behavior and measuring impact via data analysis.
  <br><br>
  
theme: jekyll-theme-minimal
google_analytics: G-LY6683ZLYC
